### ISSUE TITLE
The vgg model and the data

### ISSUE THREAD

**Issue by YCAyca** [masahi/mxnet-cpp-inference#1]
Hi! I try to use mxnet and found your repository. It looks very helpful and I want to try it with your files(.json, .params .rec files etc) before trying to adapt my own files. The google drive link that you mentioned doesnt work. Can you help me please? Thanks

**Comment by masahi** [comment]
Sorry I don't have that data anymore. You can generate your own using train_cifar10.py following [the mxnet example.](https://github.com/apache/incubator-mxnet/tree/master/example/image-classification). If you are looking for C++ api usage examples, GluonCV has [a nice tutorial](https://github.com/dmlc/gluon-cv/tree/master/scripts/deployment/cpp-inference).

**Comment by YCAyca** [comment]
Actually the reason that I ask your data was because when I try to use your cde with my own .json .params and .rec file I'm getting two errors and I wonder if it's because I'm choosing incompatible types of images and model with your code maybe. But when I try to use vgg16 model trained with cifar10 dataset I get same errors. So do you have any idea about these three errors maybe? : 
Unhandled exception at 0x00007FFC178A908C in mxnet_sample.exe: Microsoft C++ exception: dmlc::Error at memory location 0x00000072C6F5EF38.
(logging.h)

Unhandled exception thrown: read access violation.
this was 0xFFFFFFFFFFFFFFE7.
(xstring.h)

Frame not in Module (call stack message)
